/* eslint-disable */
require('./air conditioning indoor')
require('./air conditioning outdoor')
require('./alarm')
require('./bulb')
require('./cold')
require('./dome camera')
require('./door handle')
require('./doorbell')
require('./drop')
require('./electric range')
require('./eye')
require('./garage')
require('./heater')
require('./houseplant')
require('./ip camera')
require('./key')
require('./lock a')
require('./lock b')
require('./loudspeakers')
require('./nc_logo')
require('./nc-smart-home')
require('./pet')
require('./plug')
require('./pool')
require('./power button')
require('./power')
require('./recycling')
require('./remote control')
require('./router')
require('./smartphone')
require('./socket f')
require('./socket g')
require('./socket i')
require('./solar panel')
require('./sun')
require('./temperature')
require('./thermostat')
require('./tv')
require('./vacuum cleaning robot')
require('./ventilation')
require('./washer')
require('./weather')
