export const CATEGORIES = [
  {
    id: 'c1',
    name: 'Smart Light',
    icon: require('../../assets/svg/smart-bulb.svg'),
  },
  {
    id: 'c2',
    name: 'Smart TV',
    icon: require('../../assets/svg/smart-tv.svg'),
  },
  {
    id: 'c3',
    name: 'Smart Fridge',
    icon: require('../../assets/svg/fridge.svg'),
  },
  {
    id: 'c4',
    name: 'Coffee Machine',
    icon: require('../../assets/svg/coffee-maker.svg'),
  },
  {
    id: 'c5',
    name: 'Thermostat',
    icon: require('../../assets/svg/smart-thermostat.svg'),
  },
];

const DEVICES = [
  {
    id: 'd1',
    name: 'Smart Light # 1',
    brand: 'Yeelight',
    model: 'Smart Wifi Bulb',
    categoryId: 'c1',
    active: true,
    state: 'on',
    color: '#fdecf0',
    value: {
      qty: 70,
      unit: '%',
      min: 0,
      max: 100,
      label: 'Intensity',
    }, // 0 - 100
    roomId: 'r1',
    ip: '192.168.2.32',
    starred: false,
  },
  {
    id: 'd2',
    name: 'Smart Light # 2',
    brand: 'Yeelight',
    model: 'Smart Wifi Bulb',
    categoryId: 'c1',
    active: true,
    state: 'on',
    color: '#ddff00',
    value: {
      qty: 70,
      unit: '%',
      min: 0,
      max: 100,
      label: 'Intensity',
    }, // 0 - 100
    roomId: 'r1',
    ip: '192.168.2.33',
    starred: false,
  },
  {
    id: 'd3',
    name: 'Smart Light # 3',
    brand: 'Yeelight',
    model: 'Smart Wifi Bulb',
    categoryId: 'c1',
    active: false,
    state: 'on',
    color: '#ddff00',
    value: {
      qty: 70,
      unit: '%',
      min: 0,
      max: 100,
      label: 'Intensity',
    }, // 0 - 100
    roomId: 'r1',
    ip: '192.168.2.33',
    starred: false,
  },
  {
    id: 'd4',
    name: 'Smart 4K TV',
    brand: 'Samsung',
    model: 'QLED 2018 UHD 4K',
    categoryId: 'c2',
    active: true,
    state: 'on',
    value: null,
    roomId: 'r1',
    ip: '192.168.2.45',
    starred: true,
  },
  {
    id: 'd5',
    name: 'Smart Fridge',
    brand: 'Samsung',
    model: 'Double No-Frost Fridge',
    categoryId: 'c3',
    active: true,
    state: 'on',
    value: null,
    roomId: 'r1',
    ip: '192.168.3.1',
    starred: true,
  },
  {
    id: 'd6',
    name: 'Smart Lamp',
    brand: 'Yeelight',
    model: 'Smart Wifi Bulb',
    categoryId: 'c1',
    active: true,
    state: 'on',
    color: '#fdecf0',
    roomId: 'r1',
    ip: '192.168.3.2',
    starred: false,
  },
  {
    id: 'd7',
    name: 'Smart Expresso',
    brand: 'Nespresso',
    model: 'Smart Nespresso Deluxe',
    categoryId: 'c4',
    active: false,
    state: 'off',
    value: null,
    roomId: 'r1',
    ip: '192.168.3.3',
    starred: false,
  },
  {
    id: 'd8',
    name: 'Smart Thermostat',
    brand: 'Google Nest',
    model: 'Smart Thermostat wall',
    categoryId: 'c5',
    active: true,
    state: 'on',
    value: {
      qty: 22,
      unit: 'ºC',
      min: 0,
      max: 60,
      label: 'Temperature',
    },
    dataset: [22, 23, 22, 24, 22.5, 21, 19, 22],
    unit: 'ºC',
    roomId: 'r1',
    ip: '192.168.2.52',
    starred: false,
  },
];

export default DEVICES;
